### ISSUE TITLE
issue with test coverage

### ISSUE THREAD

**Issue by pauljsan** [mlnoga/nightlight#28]
Hi Markus,

I just ran the test coverage report and found only 10% of statements are covered. 

![image](https://user-images.githubusercontent.com/89738707/131254838-13d167f9-1555-462c-a939-5774c9cbedb6.png)

We need at least 95% coverage to release. Can you create a hotfix release please?

Thanks,
Paul

**Comment by mlnoga** [comment]
Sure, that should only be another six person months of spare time coding; I was actually thinking about an SELinux profile and automated OpenSCAP hardening rules for deployment in regulated industries first ;)

Welcome to GitHub, Paul ;)
