### ISSUE TITLE
Reaching Out

### ISSUE THREAD

**Issue by michael-observerly** [mlnoga/nightlight#29]
Hallo Markus! 👋 Thank you very much for this repository and your work on it thus far.

I really like the optimisations provided by this package, such as thread parallelism but mainly the in-memory approach without duplication of intermediate files.

I'm reaching out today for a few reasons: I'm not a Go programmer. But I would really like to utilise this package for a micro service I am working on that can process astronomical images. I should caveat that although the micro service won't direct being commercial, it would sit within a commercialised SaaS product. I therefore both want to sponsor this project and also help contribute to it, if you welcome contributions.

I was wondering if you would like to maybe organise a call?

**Comment by mlnoga** [comment]
Hi Michael, thank you for reaching out. Happy to explore this in a call together. What's a good way to reach you?

Best,
Markus

**Comment by michael-observerly** [comment]
@mlnoga Hi Markus. Excellent, either my email michael@observerly.com or Twitter @michealjroberts
